import z from 'zod';
import { booleanLikeSchema } from './helper.schema';

export const employeeSchema = z.object({
  employeeID: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  singleShop: booleanLikeSchema,
  hasPin: booleanLikeSchema,
  isCheckedIn: booleanLikeSchema,
  checkedInAt: z.string().optional(),
});

export const rightsSchema = z.object({
  admin: booleanLikeSchema.optional(),
  admin_employees: booleanLikeSchema.optional(),
  admin_inventory: booleanLikeSchema.optional(),
  admin_purchases: booleanLikeSchema.optional(),
  admin_shops: booleanLikeSchema.optional(),
  admin_void_sale: booleanLikeSchema.optional(),
  all_read: booleanLikeSchema.optional(),
  allow_login: booleanLikeSchema.optional(),
  categories: booleanLikeSchema.optional(),
  customers: booleanLikeSchema.optional(),
  customers_credit_limit: booleanLikeSchema.optional(),
  customers_read: booleanLikeSchema.optional(),
  ecom: booleanLikeSchema.optional(),
  inventory_base: booleanLikeSchema.optional(),
  inventory_counts: booleanLikeSchema.optional(),
  inventory_import: booleanLikeSchema.optional(),
  inventory_read: booleanLikeSchema.optional(),
  manufacturers: booleanLikeSchema.optional(),
  product_cost: booleanLikeSchema.optional(),
  product_edit: booleanLikeSchema.optional(),
  purchase_orders: booleanLikeSchema.optional(),
  register: booleanLikeSchema.optional(),
  register_catalogs: booleanLikeSchema.optional(),
  register_close: booleanLikeSchema.optional(),
  register_layaway: booleanLikeSchema.optional(),
  register_line_discount: booleanLikeSchema.optional(),
  register_open: booleanLikeSchema.optional(),
  register_price: booleanLikeSchema.optional(),
  register_read: booleanLikeSchema.optional(),
  register_refund: booleanLikeSchema.optional(),
  register_transaction_discount: booleanLikeSchema.optional(),
  register_withdraw: booleanLikeSchema.optional(),
  reports: booleanLikeSchema.optional(),
  special_orders: booleanLikeSchema.optional(),
  tags: booleanLikeSchema.optional(),
  transfers: booleanLikeSchema.optional(),
  vendor_returns: booleanLikeSchema.optional(),
  vendors: booleanLikeSchema.optional(),
  vr_reasons: booleanLikeSchema.optional(),
  workbench: booleanLikeSchema.optional(),
});

export const sessionSchema = z.object({
  sessionID: z.string().optional(),
  sessionCookie: z.string().optional(),
  employeeID: z.string(),
  systemCustomerID: z.string(),
  systemUserID: z.string(),
  systemAPIClientID: z.string(),
  systemAPIKeyID: z.string(),
  ecomUrl: z.string().optional(),
  shopCount: z.string(),
  Employee: employeeSchema,
  Rights: rightsSchema,
});
